{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-api-incubator",
    "version": "1.39.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.39.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.39.0-alpha.jar",
          "url": "opentelemetry-api-incubator-1.39.0-alpha.jar",
          "size": 37361,
          "sha512": "6da3f0fb2c38503c3e55b48ab5489eb579d142eef55f9595bff2a72fb525a98d092dd0d83229125fdb8058bd4e7c1bea919c193da9c157f124e72e053eb58776",
          "sha256": "ea84984fd86cc25b07e083af5cf39e764160bbe82ff0e2723610f8880a95af6f",
          "sha1": "1a1fd96155e1b58726300bbf8457630713035e51",
          "md5": "8b2a1676f10233e7df9c0ad55e6859f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.39.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.39.0-alpha.jar",
          "url": "opentelemetry-api-incubator-1.39.0-alpha.jar",
          "size": 37361,
          "sha512": "6da3f0fb2c38503c3e55b48ab5489eb579d142eef55f9595bff2a72fb525a98d092dd0d83229125fdb8058bd4e7c1bea919c193da9c157f124e72e053eb58776",
          "sha256": "ea84984fd86cc25b07e083af5cf39e764160bbe82ff0e2723610f8880a95af6f",
          "sha1": "1a1fd96155e1b58726300bbf8457630713035e51",
          "md5": "8b2a1676f10233e7df9c0ad55e6859f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.39.0-alpha-javadoc.jar",
          "url": "opentelemetry-api-incubator-1.39.0-alpha-javadoc.jar",
          "size": 158496,
          "sha512": "ffceacd4bae620415bf8cea608bb9952bda83d0d29b73aed551c59758ddc10849159733323e0533ec203e047c8729ea1fd982835ea5e61370841d8a8062d9f02",
          "sha256": "5cb970a870c64a9bfe1a7fb84694ef5e82f5c4e411f44f5aeb767c69137aa48c",
          "sha1": "491aad8fb3086aae6a3bb196e54b286ce3989ba7",
          "md5": "eabbdea4c30f2d6f876f0644ec3ad29e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.39.0-alpha-sources.jar",
          "url": "opentelemetry-api-incubator-1.39.0-alpha-sources.jar",
          "size": 25667,
          "sha512": "519baedf3679f280ecdb716160890abc014f909b2b5e1daf8cd5b0494b46e8f57288ea8d8e2d0416748198e4291012f433f5461262c2c828e93f6637eb6b6688",
          "sha256": "7973468a58546e624ccd6ebe04da07fbd5638fda371d1c5cf596dd2714fcc758",
          "sha1": "379ea7a6458548624749ab0afa3efcd6b00edaba",
          "md5": "9e5e9c4a2dfe8a388071b24444906494"
        }
      ]
    }
  ]
}
