{
  "formatVersion": "1.1",
  "component": {
    "group": "org.testng",
    "module": "testng",
    "version": "7.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.82"
          }
        }
      ],
      "files": [
        {
          "name": "testng-7.8.0.jar",
          "url": "testng-7.8.0.jar",
          "size": 1019729,
          "sha512": "0c0e8958271b32c40468183e554c9e7c871490007e4e23d9e24a2f3470912d7a5a5c0190d30504c76d67c32b76054d69831c8805a0ea79104d9daa129a494dc2",
          "sha256": "dbbc43e2c64623661c3537f9d74061eb6c8fc3e5b4376f31fadb16de2b200f88",
          "sha1": "90ff6902a350432ce23ef209b2f109bcf587069c",
          "md5": "816c07722c4fbd2e734a5c36a2f0cade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.82"
          }
        },
        {
          "group": "org.webjars",
          "module": "jquery",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "testng-7.8.0.jar",
          "url": "testng-7.8.0.jar",
          "size": 1019729,
          "sha512": "0c0e8958271b32c40468183e554c9e7c871490007e4e23d9e24a2f3470912d7a5a5c0190d30504c76d67c32b76054d69831c8805a0ea79104d9daa129a494dc2",
          "sha256": "dbbc43e2c64623661c3537f9d74061eb6c8fc3e5b4376f31fadb16de2b200f88",
          "sha1": "90ff6902a350432ce23ef209b2f109bcf587069c",
          "md5": "816c07722c4fbd2e734a5c36a2f0cade"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testng-7.8.0-javadoc.jar",
          "url": "testng-7.8.0-javadoc.jar",
          "size": 1188960,
          "sha512": "35d1b25b2cd70735fb4f5ff4264939163756687376c85911470a2cea27114af226a0a76cdf7458014741b5bf41d641a5f63a6f2b5b36ce03ab92f2a672c585ad",
          "sha256": "03b659f5ec7eb5907a682a3a2a6c636ee073d6bdbe5e441316cec7e81ca598e1",
          "sha1": "e1bbc7a2cdf3982ed82de36991ea73e1a817475b",
          "md5": "c469dd93af1763693196a66bab64e507"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testng-7.8.0-sources.jar",
          "url": "testng-7.8.0-sources.jar",
          "size": 507521,
          "sha512": "53574e14e1e76f0aa6f098f2fd4de86583ae51f9630e2a15a612e99ab199ec49ed730d9e229eadf31be981903ceb0a09aa296d6119c27d099ad2647ddbc40b6e",
          "sha256": "e67f21faf87828b351c8e63e3dd229e99c0e78c1a916f4fdbe9a85f2cace8c0a",
          "sha1": "78aa9832674fd6a21375e8a9ee82fbbe9ffcde3a",
          "md5": "5e7bc1aacf7ca91d9aa926886a1a5d19"
        }
      ]
    },
    {
      "name": "antApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.12"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-ant",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "antRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.12"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.82"
          }
        },
        {
          "group": "org.webjars",
          "module": "jquery",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-ant",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "guiceApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice-bom",
          "version": {
            "requires": "5.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-guice",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "guiceRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice-bom",
          "version": {
            "requires": "5.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-guice",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "junitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-junit",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "junitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-junit",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "yamlApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-yaml",
          "version": "7.8.0"
        }
      ]
    },
    {
      "name": "yamlRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-yaml",
          "version": "7.8.0"
        }
      ]
    }
  ]
}
